<?php
    $arregloUnidadNoPeso = array('cucharada', 'cucharadita', 'lata', 'taza', 'unidad');
    define('TIPO_ORIGEN_RS28', 'RS/28');
    define('TIPO_ORIGEN_MINSA', 'Minsa');
    define('APORTE_POSITIVO', 'positivo');
    define('APORTE_NEGATIVO', 'negativo');
    define('APORTE_AMBOS', 'ambos');
    define('INSUMO_IMAGE_SHORT_PATH', 'imagen/insumo/');
    define('EXCEL_INSUMO_PATH', 'excel/insumo/');
    define('UPLOAD_INSUMO_IMAGEN', 'insumo_img');
    define('UPLOAD_INSUMO_MEDIDA', 'insumo_medida');
    define('MEDIDA_CUCHARADA', 'cucharada');
    define('MEDIDA_CUCHARADITA', 'cucharadita');
    define('MEDIDA_LATA', 'lata');
    define('MEDIDA_TAZA', 'taza');
    define('MEDIDA_UNIDAD', 'unidad');
    define('INSUMO_IMAGE_REMOTE_PATH', 'ingredient/');
    define('TIPO_ALIMENTO_IMAGE_REMOTE_PATH', 'foodtype/');
    define('FOLDER_IMAGE_204x140', '204x140/');
    define('FOLDER_IMAGE_215x148', '215x148/');
    define('FOLDER_IMAGE_276x190', '276x190/');
    define('FOLDER_IMAGE_214x250', '214x250/');
    define('FOLDER_IMAGE_185x250', '185x250/');
    define('FOLDER_IMAGE_348x200', '348x200/');
    define('FOLDER_IMAGE_208x200', '208x200/');
    define('FOLDER_IMAGE_276x200', '276x200/');
    define('PREFIX_IMAGE_SMALL', '170x120');
    define('PREFIX_IMAGE_MEDIUM', '200x150');
    define('PREFIX_IMAGE_LARGE', '230x180');
    define('WIDTH_IMAGE_SMALL', '170w');
    define('WIDTH_IMAGE_MEDIUM', '200w');
    define('WIDTH_IMAGE_LARGE', '230w');
    define('SIZE_IMAGE_SET', '(max-width: 640px) 170px, (max-width: 1024px) 200px, 230px');
    define('ICONO_INSUMO_ROJO', 'icono_rojo.png');
    define('ICONO_INSUMO_AMARILLO', 'icono_amarillo.png');
    define('ICONO_INSUMO_VERDE', 'icono_verde.png');
    define('ICONO_INSUMO_AZUL', 'icono_azul.png');
    define('INSUMO_FOLDER_MINIATURA', '50x50/');
    define('PREFIX_INSUMO_IMAGE_MINIATURA', '50x50');

    define('TEXTO_SEMA_ROJO', 'Debe eliminar este ingrediente en su dieta.');
    define('TEXTO_SEMA_AMARILLO', 'Debe restringir este ingrediente en su dieta.');
    define('TEXTO_SEMA_VERDE', 'Puede consumir normalmente.');
    define('TEXTO_SEMA_AZUL', 'Debe aumentar este ingrediente en su dieta');
    define('TEXTO_SEMA_ROJO_ING', 'You must eliminate this ingredient in your diet.');
    define('TEXTO_SEMA_AMARILLO_ING', 'You must restrict this ingredient in your diet.');
    define('TEXTO_SEMA_VERDE_ING', 'You can consume normally.');
    define('TEXTO_SEMA_AZUL_ING', 'You must increase this ingredient in your diet.');
?>
